import 'dart:convert';
import 'dart:io';

import 'package:flutter_clean_arch/flutter_clean_arch.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  late TemplateGenerator generator;
  late Directory dir;
  late FlutterProject project;

  setUpAll(() async => generator = await TemplateGenerator.locate());

  String read(String relative) =>
      File(p.join(dir.path, relative)).readAsStringSync();

  setUp(() {
    dir = Directory.systemTemp.createTempSync('fca_auth_');
    writeAll(dir.path, [
      const RenderedFile(
        'pubspec.yaml',
        'name: demo_app\ndependencies:\n  flutter:\n    sdk: flutter\n',
      ),
      ...generator.render('init', {
        'package': 'demo_app',
        'todoTag': 'demo-app',
        'appTitle': 'Demo App',
      }),
    ]);
    project = FlutterProject.load(dir.path);
  });
  tearDown(() => dir.deleteSync(recursive: true));

  test('patches every base file', () {
    applyAuthChanges(project, generator);

    expect(read('lib/features/auth/auth.dart'), contains('library;'));
    expect(
      read('lib/bootstrap.dart'),
      allOf(
        contains('required FirebaseOptions firebaseOptions'),
        contains('await Firebase.initializeApp(options: firebaseOptions);'),
        contains('await initDependencies(firebaseOptions: firebaseOptions);'),
      ),
    );
    for (final flavor in authFlavors) {
      expect(
        read('lib/main_$flavor.dart'),
        contains('firebaseOptionsFor(AppFlavor.$flavor)'),
      );
      expect(
        read('lib/core/firebase/firebase_options_$flavor.dart'),
        contains('class DefaultFirebaseOptions'),
      );
    }
    expect(
      read('lib/core/di/injection_container.dart'),
      allOf(
        contains('required FirebaseOptions firebaseOptions'),
        contains(
          'await initAuthDependencies(firebaseOptions: firebaseOptions);',
        ),
      ),
    );
    expect(
      read('lib/core/router/app_routes.dart'),
      allOf(contains("login = '/login'"), contains(r"startsWith('$login/')")),
    );
    expect(
      read('lib/core/router/app_router.dart'),
      allOf(
        contains(
          'static final GoRouter instance = _create(getIt<AuthBloc>());',
        ),
        contains('refreshListenable: GoRouterRefreshStream(authBloc.stream)'),
        contains('page: const LoginPage()'),
        contains(Markers.routes),
      ),
    );
    expect(
      read('lib/app/pages/app.dart'),
      allOf(
        contains('value: getIt<AuthBloc>()'),
        contains('child: MaterialApp.router('),
      ),
    );
    expect(
      read('lib/features/home/presentation/pages/home/home_page.dart'),
      contains('AuthSignOutRequested'),
    );

    final en = jsonDecode(read('lib/core/l10n/arb/app_en.arb')) as Map;
    expect(en['homeTitle'], 'Demo App');
    expect(en['loginSubtitle'], 'Welcome back to Demo App');
  });

  test('is idempotent and keeps real Firebase options', () {
    const real = '// File generated by FlutterFire CLI.\n';
    File(p.join(dir.path, 'lib/core/firebase/firebase_options_staging.dart'))
      ..createSync(recursive: true)
      ..writeAsStringSync(real);

    applyAuthChanges(project, generator);
    final once = {
      for (final f in [
        'lib/bootstrap.dart',
        'lib/core/di/injection_container.dart',
        'lib/core/router/app_router.dart',
        'lib/core/router/app_routes.dart',
        'lib/app/pages/app.dart',
        'lib/core/l10n/arb/app_es.arb',
      ])
        f: read(f),
    };
    applyAuthChanges(project, generator);

    once.forEach((file, content) => expect(read(file), content, reason: file));
    expect(read('lib/core/firebase/firebase_options_staging.dart'), real);
  });
}
